url: "https://lars.hupel.info"
logo: "/img/profile.jpg"
title: "Lars Hupel's website"
author:
  name: "Lars Hupel"
  twitter: "larsr_h"
  uri: "https://lars.hupel.info"
  picture: "/img/profile.jpg"
twitter:
  username: "larsr_h"
social:
  links:
    - "https://github.com/larsrh"
    - "https://twitter.com/larsr_h"
    - "https://instagram.com/larsr_h"
    - "https://keybase.io/larsrh"
    - "https://stackoverflow.com/users/4776939/larsrh"
include:
  - "_redirects"
exclude:
  - "img_assets"
  - "scripts"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
  - ".ruby-version"
  - ".ci"
  - "venv"
encoding: "utf-8"

collections:
  articles:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/
  talks:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: articles
    values:
      layout: article
      nav: articles
      card_theme: bg-dark text-white
      is_article: true
      description: ""
  - scope:
      path: ""
      type: research
    values:
      layout: research
      nav: academic
      card_theme: bg-success text-white
      is_research: true
      description: ""
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      nav: activities
      is_talk: true
      description: ""
  - scope:
      path: "topics/crdt"
    values:
      long_title: An introduction to Conflict-Free Replicated Datatypes
      layout: article
      nav: articles
      description: ""
      toc: true
      lang: en
      codemirror:
        - /js/html.js
        - /js/articles/crdt/fc.js
        - /js/articles/crdt/chai.js
        - /js/articles/crdt/fc-runner.js
      abstract: |
        This is an ongoing series about Conflict-Free Replicated Datatypes, or CRDTs for short.
        Their purpose is to allow seamless replication of data on different nodes in a distributed system.
        Merging is by construction always possible, without any conflicts.
        This series assumes no knowledge about CRDTs, but be prepared to learn a thing or two about algebras.
        All code samples on this page are interactive and executed in your browser.
        Understanding the code is necessary for understanding the concepts, so you should be familiar with JavaScript.
        If you notice any bugs on this page, [please let me know](https://github.com/larsrh/website/issues)!
